export interface MicroprintPattern {
  id: number;
  name: string;
  category: string;
  description: string;
  // How to arrange text: function returns array of {x, y, angle, scale} for each text instance
  layout: "linear" | "wave" | "spiral" | "grid" | "radial" | "diagonal" | "zigzag" | "circular" | "random" | "custom";
  layoutParams: Record<string, number | string | boolean>;
}

export const MICROPRINT_PATTERNS: MicroprintPattern[] = [
  // LINEAR PATTERNS (1-10)
  {
    id: 1,
    name: "Classic Horizontal",
    category: "Linear",
    description: "Simple horizontal lines of text",
    layout: "linear",
    layoutParams: { direction: "horizontal", spacing: 1.0 },
  },
  {
    id: 2,
    name: "Tight Horizontal",
    category: "Linear",
    description: "Densely packed horizontal lines",
    layout: "linear",
    layoutParams: { direction: "horizontal", spacing: 0.7 },
  },
  {
    id: 3,
    name: "Vertical Lines",
    category: "Linear",
    description: "Text arranged in vertical columns",
    layout: "linear",
    layoutParams: { direction: "vertical", spacing: 1.0 },
  },
  {
    id: 4,
    name: "Diagonal 45°",
    category: "Linear",
    description: "Text at 45 degree angle",
    layout: "diagonal",
    layoutParams: { angle: 45, spacing: 1.0 },
  },
  {
    id: 5,
    name: "Diagonal -45°",
    category: "Linear",
    description: "Text at -45 degree angle",
    layout: "diagonal",
    layoutParams: { angle: -45, spacing: 1.0 },
  },
  {
    id: 6,
    name: "Diagonal 30°",
    category: "Linear",
    description: "Text at 30 degree angle",
    layout: "diagonal",
    layoutParams: { angle: 30, spacing: 1.0 },
  },
  {
    id: 7,
    name: "Diagonal 60°",
    category: "Linear",
    description: "Text at 60 degree angle",
    layout: "diagonal",
    layoutParams: { angle: 60, spacing: 1.0 },
  },
  {
    id: 8,
    name: "Cross-hatch",
    category: "Linear",
    description: "Two overlapping diagonal directions",
    layout: "diagonal",
    layoutParams: { angle: 45, spacing: 1.0, crosshatch: true },
  },
  {
    id: 9,
    name: "Double Horizontal",
    category: "Linear",
    description: "Alternating normal and mirrored horizontal lines",
    layout: "linear",
    layoutParams: { direction: "horizontal", spacing: 1.0, alternateFlip: true },
  },
  {
    id: 10,
    name: "Staggered Rows",
    category: "Linear",
    description: "Horizontal rows with alternating offsets",
    layout: "linear",
    layoutParams: { direction: "horizontal", spacing: 1.0, stagger: 0.5 },
  },

  // WAVE PATTERNS (11-20)
  {
    id: 11,
    name: "Sine Wave",
    category: "Wave",
    description: "Text following a sine wave path",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 0 },
  },
  {
    id: 12,
    name: "Double Sine Wave",
    category: "Wave",
    description: "Two interleaved sine waves",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 0, double: true },
  },
  {
    id: 13,
    name: "High Amplitude Wave",
    category: "Wave",
    description: "Sine wave with large amplitude",
    layout: "wave",
    layoutParams: { amplitude: 40, frequency: 0.015, phase: 0 },
  },
  {
    id: 14,
    name: "Fast Wave",
    category: "Wave",
    description: "Rapidly oscillating sine wave",
    layout: "wave",
    layoutParams: { amplitude: 15, frequency: 0.04, phase: 0 },
  },
  {
    id: 15,
    name: "Cosine Wave",
    category: "Wave",
    description: "Text following a cosine wave",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 1.5708 },
  },
  {
    id: 16,
    name: "Wave Grid",
    category: "Wave",
    description: "Multiple wave rows forming a grid",
    layout: "wave",
    layoutParams: { amplitude: 10, frequency: 0.03, phase: 0, multiRow: true },
  },
  {
    id: 17,
    name: "Opposing Waves",
    category: "Wave",
    description: "Alternating rows with opposite wave phases",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 0, alternatePhase: true },
  },
  {
    id: 18,
    name: "Ripple",
    category: "Wave",
    description: "Concentric ripple-like wave pattern",
    layout: "wave",
    layoutParams: { amplitude: 8, frequency: 0.05, phase: 0, ripple: true },
  },
  {
    id: 19,
    name: "Sawtooth Wave",
    category: "Wave",
    description: "Text following a sawtooth wave",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 0, sawtooth: true },
  },
  {
    id: 20,
    name: "Square Wave",
    category: "Wave",
    description: "Text following a square wave path",
    layout: "wave",
    layoutParams: { amplitude: 20, frequency: 0.02, phase: 0, square: true },
  },

  // SPIRAL PATTERNS (21-30)
  {
    id: 21,
    name: "Archimedean Spiral",
    category: "Spiral",
    description: "Text spiraling outward from center",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 15, turns: 8 },
  },
  {
    id: 22,
    name: "Tight Spiral",
    category: "Spiral",
    description: "Densely packed spiral",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 10, turns: 12 },
  },
  {
    id: 23,
    name: "Loose Spiral",
    category: "Spiral",
    description: "Widely spaced spiral",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 25, turns: 5 },
  },
  {
    id: 24,
    name: "Double Spiral",
    category: "Spiral",
    description: "Two interleaved spirals",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 20, turns: 6, double: true },
  },
  {
    id: 25,
    name: "Logarithmic Spiral",
    category: "Spiral",
    description: "Text following a logarithmic spiral",
    layout: "spiral",
    layoutParams: { type: "logarithmic", growth: 0.15, turns: 4 },
  },
  {
    id: 26,
    name: "Reverse Spiral",
    category: "Spiral",
    description: "Spiral going inward from edge",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 15, turns: 8, reverse: true },
  },
  {
    id: 27,
    name: "Spiral Galaxy",
    category: "Spiral",
    description: "Multiple arms like a galaxy",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 20, turns: 5, arms: 3 },
  },
  {
    id: 28,
    name: "Fibonacci Spiral",
    category: "Spiral",
    description: "Golden ratio spiral",
    layout: "spiral",
    layoutParams: { type: "fibonacci", turns: 6 },
  },
  {
    id: 29,
    name: "Hypnotic Spiral",
    category: "Spiral",
    description: "Alternating text direction spiral",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 15, turns: 8, alternateDir: true },
  },
  {
    id: 30,
    name: "Expanding Spiral",
    category: "Spiral",
    description: "Spiral with increasing text size",
    layout: "spiral",
    layoutParams: { type: "archimedean", spacing: 18, turns: 6, expandText: true },
  },

  // GRID PATTERNS (31-40)
  {
    id: 31,
    name: "Square Grid",
    category: "Grid",
    description: "Text arranged in a perfect square grid",
    layout: "grid",
    layoutParams: { type: "square", spacing: 1.0 },
  },
  {
    id: 32,
    name: "Hexagonal Grid",
    category: "Grid",
    description: "Text in hexagonal arrangement",
    layout: "grid",
    layoutParams: { type: "hex", spacing: 1.0 },
  },
  {
    id: 33,
    name: "Diamond Grid",
    category: "Grid",
    description: "Text rotated 45° in grid",
    layout: "grid",
    layoutParams: { type: "diamond", spacing: 1.0 },
  },
  {
    id: 34,
    name: "Brick Pattern",
    category: "Grid",
    description: "Staggered brick-like arrangement",
    layout: "grid",
    layoutParams: { type: "brick", spacing: 1.0 },
  },
  {
    id: 35,
    name: "Triangular Grid",
    category: "Grid",
    description: "Text in triangular arrangement",
    layout: "grid",
    layoutParams: { type: "triangle", spacing: 1.0 },
  },
  {
    id: 36,
    name: "Scattered Grid",
    category: "Grid",
    description: "Grid with random small offsets",
    layout: "grid",
    layoutParams: { type: "square", spacing: 1.0, scatter: 0.3 },
  },
  {
    id: 37,
    name: "Rotated Grid",
    category: "Grid",
    description: "Grid rotated 15 degrees",
    layout: "grid",
    layoutParams: { type: "square", spacing: 1.0, rotation: 15 },
  },
  {
    id: 38,
    name: "Dense Hex Grid",
    category: "Grid",
    description: "Tightly packed hexagonal grid",
    layout: "grid",
    layoutParams: { type: "hex", spacing: 0.7 },
  },
  {
    id: 39,
    name: "Alternating Grid",
    category: "Grid",
    description: "Grid with alternating text orientations",
    layout: "grid",
    layoutParams: { type: "square", spacing: 1.0, alternateAngle: 90 },
  },
  {
    id: 40,
    name: "Perspective Grid",
    category: "Grid",
    description: "Grid with perspective-like scaling",
    layout: "grid",
    layoutParams: { type: "perspective", spacing: 1.0 },
  },

  // RADIAL PATTERNS (41-50)
  {
    id: 41,
    name: "Sunburst",
    category: "Radial",
    description: "Text radiating from center",
    layout: "radial",
    layoutParams: { type: "sunburst", rings: 8 },
  },
  {
    id: 42,
    name: "Concentric Circles",
    category: "Radial",
    description: "Text in concentric circular rings",
    layout: "radial",
    layoutParams: { type: "concentric", rings: 10 },
  },
  {
    id: 43,
    name: "Pinwheel",
    category: "Radial",
    description: "Text arranged like pinwheel blades",
    layout: "radial",
    layoutParams: { type: "pinwheel", blades: 8, rings: 6 },
  },
  {
    id: 44,
    name: "Mandala",
    category: "Radial",
    description: "Symmetric mandala-like pattern",
    layout: "radial",
    layoutParams: { type: "mandala", symmetry: 8, rings: 5 },
  },
  {
    id: 45,
    name: "Starburst",
    category: "Radial",
    description: "Star-shaped radial pattern",
    layout: "radial",
    layoutParams: { type: "starburst", points: 12, rings: 6 },
  },
  {
    id: 46,
    name: "Vortex",
    category: "Radial",
    description: "Rotating vortex pattern",
    layout: "radial",
    layoutParams: { type: "vortex", twist: 0.5, rings: 8 },
  },
  {
    id: 47,
    name: "Target",
    category: "Radial",
    description: "Bullseye target pattern",
    layout: "radial",
    layoutParams: { type: "target", rings: 12 },
  },
  {
    id: 48,
    name: "Flower",
    category: "Radial",
    description: "Flower petal arrangement",
    layout: "radial",
    layoutParams: { type: "flower", petals: 6, rings: 5 },
  },
  {
    id: 49,
    name: "Web",
    category: "Radial",
    description: "Spider web-like pattern",
    layout: "radial",
    layoutParams: { type: "web", spokes: 12, rings: 8 },
  },
  {
    id: 50,
    name: "Compass Rose",
    category: "Radial",
    description: "Compass rose arrangement",
    layout: "radial",
    layoutParams: { type: "compass", rings: 6 },
  },

  // ZIGZAG PATTERNS (51-60)
  {
    id: 51,
    name: "Zigzag Horizontal",
    category: "Zigzag",
    description: "Text in horizontal zigzag rows",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 20, frequency: 0.05 },
  },
  {
    id: 52,
    name: "Zigzag Vertical",
    category: "Zigzag",
    description: "Text in vertical zigzag columns",
    layout: "zigzag",
    layoutParams: { direction: "vertical", amplitude: 20, frequency: 0.05 },
  },
  {
    id: 53,
    name: "Double Zigzag",
    category: "Zigzag",
    description: "Two interleaved zigzag patterns",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 20, frequency: 0.05, double: true },
  },
  {
    id: 54,
    name: "Chevron",
    category: "Zigzag",
    description: "Chevron-shaped text arrangement",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 30, frequency: 0.03, chevron: true },
  },
  {
    id: 55,
    name: "Lightning Bolt",
    category: "Zigzag",
    description: "Sharp lightning bolt pattern",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 40, frequency: 0.02, sharp: true },
  },
  {
    id: 56,
    name: "Herringbone",
    category: "Zigzag",
    description: "Herringbone weave pattern",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 15, frequency: 0.04, herringbone: true },
  },
  {
    id: 57,
    name: "Cascade",
    category: "Zigzag",
    description: "Cascading diagonal zigzag",
    layout: "zigzag",
    layoutParams: { direction: "diagonal", amplitude: 20, frequency: 0.04 },
  },
  {
    id: 58,
    name: "Staircase",
    category: "Zigzag",
    description: "Staircase-like step pattern",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 20, frequency: 0.03, staircase: true },
  },
  {
    id: 59,
    name: "Crenellation",
    category: "Zigzag",
    description: "Castle battlement pattern",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 25, frequency: 0.025, crenellation: true },
  },
  {
    id: 60,
    name: "Diamond Chain",
    category: "Zigzag",
    description: "Diamond-shaped chain pattern",
    layout: "zigzag",
    layoutParams: { direction: "horizontal", amplitude: 20, frequency: 0.04, diamond: true },
  },

  // CIRCULAR PATTERNS (61-70)
  {
    id: 61,
    name: "Circle Text",
    category: "Circular",
    description: "Text arranged in a single circle",
    layout: "circular",
    layoutParams: { type: "single", radius: 0.4 },
  },
  {
    id: 62,
    name: "Nested Circles",
    category: "Circular",
    description: "Multiple concentric text circles",
    layout: "circular",
    layoutParams: { type: "nested", count: 6 },
  },
  {
    id: 63,
    name: "Oval",
    category: "Circular",
    description: "Text arranged in an oval",
    layout: "circular",
    layoutParams: { type: "oval", radiusX: 0.45, radiusY: 0.3 },
  },
  {
    id: 64,
    name: "Figure Eight",
    category: "Circular",
    description: "Text following a figure-8 path",
    layout: "circular",
    layoutParams: { type: "figure8", scale: 0.35 },
  },
  {
    id: 65,
    name: "Trefoil",
    category: "Circular",
    description: "Three-lobed trefoil pattern",
    layout: "circular",
    layoutParams: { type: "trefoil", scale: 0.3 },
  },
  {
    id: 66,
    name: "Lemniscate",
    category: "Circular",
    description: "Infinity symbol path",
    layout: "circular",
    layoutParams: { type: "lemniscate", scale: 0.4 },
  },
  {
    id: 67,
    name: "Cardioid",
    category: "Circular",
    description: "Heart-shaped cardioid curve",
    layout: "circular",
    layoutParams: { type: "cardioid", scale: 0.3 },
  },
  {
    id: 68,
    name: "Rose Curve",
    category: "Circular",
    description: "Rose curve (rhodonea) pattern",
    layout: "circular",
    layoutParams: { type: "rose", petals: 4, scale: 0.4 },
  },
  {
    id: 69,
    name: "Epicycloid",
    category: "Circular",
    description: "Epicycloid curve pattern",
    layout: "circular",
    layoutParams: { type: "epicycloid", k: 3, scale: 0.3 },
  },
  {
    id: 70,
    name: "Hypotrochoid",
    category: "Circular",
    description: "Spirograph-like hypotrochoid",
    layout: "circular",
    layoutParams: { type: "hypotrochoid", R: 5, r: 3, d: 5, scale: 0.08 },
  },

  // RANDOM/ORGANIC PATTERNS (71-80)
  {
    id: 71,
    name: "Random Scatter",
    category: "Organic",
    description: "Randomly scattered text",
    layout: "random",
    layoutParams: { type: "scatter", seed: 42 },
  },
  {
    id: 72,
    name: "Perlin Noise",
    category: "Organic",
    description: "Text following Perlin noise flow",
    layout: "random",
    layoutParams: { type: "perlin", scale: 0.005, seed: 1 },
  },
  {
    id: 73,
    name: "Brownian Motion",
    category: "Organic",
    description: "Random walk pattern",
    layout: "random",
    layoutParams: { type: "brownian", steps: 200, seed: 7 },
  },
  {
    id: 74,
    name: "Cluster",
    category: "Organic",
    description: "Text clustered in groups",
    layout: "random",
    layoutParams: { type: "cluster", clusters: 5, seed: 13 },
  },
  {
    id: 75,
    name: "Organic Flow",
    category: "Organic",
    description: "Organic flowing lines",
    layout: "random",
    layoutParams: { type: "flow", seed: 21 },
  },
  {
    id: 76,
    name: "Constellation",
    category: "Organic",
    description: "Star constellation-like pattern",
    layout: "random",
    layoutParams: { type: "constellation", seed: 33 },
  },
  {
    id: 77,
    name: "Fractal Noise",
    category: "Organic",
    description: "Fractal-based noise pattern",
    layout: "random",
    layoutParams: { type: "fractal", octaves: 4, seed: 55 },
  },
  {
    id: 78,
    name: "Voronoi",
    category: "Organic",
    description: "Voronoi cell-based arrangement",
    layout: "random",
    layoutParams: { type: "voronoi", cells: 20, seed: 89 },
  },
  {
    id: 79,
    name: "Reaction Diffusion",
    category: "Organic",
    description: "Turing pattern-inspired layout",
    layout: "random",
    layoutParams: { type: "turing", seed: 144 },
  },
  {
    id: 80,
    name: "Poisson Disk",
    category: "Organic",
    description: "Evenly distributed random points",
    layout: "random",
    layoutParams: { type: "poisson", minDist: 30, seed: 233 },
  },

  // SPECIAL/ARTISTIC PATTERNS (81-100)
  {
    id: 81,
    name: "DNA Helix",
    category: "Special",
    description: "Double helix DNA pattern",
    layout: "custom",
    layoutParams: { type: "dna", pitch: 60, radius: 30 },
  },
  {
    id: 82,
    name: "Maze",
    category: "Special",
    description: "Text following maze-like paths",
    layout: "custom",
    layoutParams: { type: "maze", cellSize: 40 },
  },
  {
    id: 83,
    name: "Topographic",
    category: "Special",
    description: "Topographic contour lines",
    layout: "custom",
    layoutParams: { type: "topo", levels: 8 },
  },
  {
    id: 84,
    name: "Fingerprint",
    category: "Special",
    description: "Fingerprint whorl pattern",
    layout: "custom",
    layoutParams: { type: "fingerprint", loops: 12 },
  },
  {
    id: 85,
    name: "Circuit Board",
    category: "Special",
    description: "PCB circuit board traces",
    layout: "custom",
    layoutParams: { type: "circuit", density: 0.6 },
  },
  {
    id: 86,
    name: "Barcode",
    category: "Special",
    description: "Barcode-inspired vertical lines",
    layout: "custom",
    layoutParams: { type: "barcode", variation: 0.3 },
  },
  {
    id: 87,
    name: "Woven Fabric",
    category: "Special",
    description: "Woven textile pattern",
    layout: "custom",
    layoutParams: { type: "weave", over: 2, under: 2 },
  },
  {
    id: 88,
    name: "Knot",
    category: "Special",
    description: "Celtic knot-inspired pattern",
    layout: "custom",
    layoutParams: { type: "knot", complexity: 3 },
  },
  {
    id: 89,
    name: "Penrose Tiling",
    category: "Special",
    description: "Penrose tiling arrangement",
    layout: "custom",
    layoutParams: { type: "penrose", iterations: 4 },
  },
  {
    id: 90,
    name: "Lissajous",
    category: "Special",
    description: "Lissajous curve pattern",
    layout: "circular",
    layoutParams: { type: "lissajous", a: 3, b: 2, delta: 1.5708, scale: 0.4 },
  },
  {
    id: 91,
    name: "Phyllotaxis",
    category: "Special",
    description: "Sunflower seed arrangement",
    layout: "custom",
    layoutParams: { type: "phyllotaxis", scale: 4 },
  },
  {
    id: 92,
    name: "Truchet Tiles",
    category: "Special",
    description: "Truchet tile-based curves",
    layout: "custom",
    layoutParams: { type: "truchet", tileSize: 40 },
  },
  {
    id: 93,
    name: "Moiré Pattern",
    category: "Special",
    description: "Overlapping line moiré effect",
    layout: "custom",
    layoutParams: { type: "moire", angle1: 0, angle2: 5 },
  },
  {
    id: 94,
    name: "Interference",
    category: "Special",
    description: "Wave interference pattern",
    layout: "custom",
    layoutParams: { type: "interference", sources: 3 },
  },
  {
    id: 95,
    name: "Diffraction",
    category: "Special",
    description: "Light diffraction grating",
    layout: "custom",
    layoutParams: { type: "diffraction", slits: 5 },
  },
  {
    id: 96,
    name: "Meander",
    category: "Special",
    description: "Greek meander border pattern",
    layout: "custom",
    layoutParams: { type: "meander", depth: 3 },
  },
  {
    id: 97,
    name: "Hilbert Curve",
    category: "Special",
    description: "Space-filling Hilbert curve",
    layout: "custom",
    layoutParams: { type: "hilbert", order: 4 },
  },
  {
    id: 98,
    name: "Dragon Curve",
    category: "Special",
    description: "Fractal dragon curve",
    layout: "custom",
    layoutParams: { type: "dragon", iterations: 10 },
  },
  {
    id: 99,
    name: "Gosper Curve",
    category: "Special",
    description: "Gosper flowsnake fractal",
    layout: "custom",
    layoutParams: { type: "gosper", iterations: 3 },
  },
  {
    id: 100,
    name: "Chaos Attractor",
    category: "Special",
    description: "Strange attractor pattern",
    layout: "custom",
    layoutParams: { type: "lorenz", dt: 0.01, steps: 5000 },
  },
];

export const PATTERN_CATEGORIES = [
  "All",
  "Linear",
  "Wave",
  "Spiral",
  "Grid",
  "Radial",
  "Zigzag",
  "Circular",
  "Organic",
  "Special",
];
